import type { Workspace } from "../app/state";
import type { Operations } from "../app/operations";
import { bytes, emptyState, escape, icon, notice } from "../components/html";

export type DumpSort = "newest" | "oldest" | "name" | "size";

export function dumpRows(state: Workspace, operations: Operations, search: string, sort: DumpSort, busy: Set<string>): string {
  const dumps = state.dumps.data.filter(dump => dump.name.toLocaleLowerCase().includes(search.toLocaleLowerCase())).sort((a, b) => sort === "name" ? a.name.localeCompare(b.name) : sort === "size" ? b.size - a.size : sort === "oldest" ? a.modTime.localeCompare(b.modTime) : b.modTime.localeCompare(a.modTime));
  if (state.dumps.loading && !state.dumps.data.length) return '<div class="workspace-loading"><span class="spinner"></span><p>Loading dumps...</p></div>';
  if (!dumps.length) return emptyState(search ? "No matching dumps" : "No dumps yet", search ? "Try another filename or clear the search." : "Export a database to add a file to this library.", !search ? `<button data-action="navigate" data-view="workspace">${icon("database")} Go to workspace</button>` : "", "folder");
  return `<div class="table-scroll"><table class="dump-table"><thead><tr><th scope="col">Filename</th><th scope="col">Size</th><th scope="col">Modified</th><th scope="col"><span class="sr-only">Actions</span></th></tr></thead><tbody>${dumps.map((dump, index) => {
    const locked = busy.has(dump.name) || operations.active?.librarySource && operations.active.sourceName === dump.name;
    const date = new Date(dump.modTime);
    return `<tr><td><div class="dump-filename">${icon("file")}<div><strong class="mono" title="${escape(dump.name)}">${escape(dump.name)}</strong><details class="file-details"><summary>File details</summary><dl><dt>Path</dt><dd class="mono">${escape(dump.path || dump.name)}</dd><dt>Size</dt><dd>${dump.size.toLocaleString()} bytes</dd></dl><button class="small" data-action="copy-path" data-name="${escape(dump.name)}">Copy path</button></details></div></div></td><td class="size-cell">${bytes(dump.size)}</td><td class="date-cell"><time datetime="${escape(dump.modTime)}" title="${escape(dump.modTime)}">${escape(Number.isNaN(date.getTime()) ? dump.modTime : date.toLocaleString(undefined, { month: "short", day: "numeric", hour: "2-digit", minute: "2-digit", year: "numeric" }))}</time></td><td><div class="row-actions"><button class="small quiet" id="dump-restore-${index}" data-action="restore-file" data-name="${escape(dump.name)}" ${busy.has(dump.name) ? "disabled" : ""}>Restore</button><details class="action-menu"><summary class="icon-button" aria-label="Actions for ${escape(dump.name)}">${icon("more")}</summary><div class="menu-items"><button data-action="download-file" data-name="${escape(dump.name)}" ${busy.has(dump.name) ? "disabled" : ""}>${state.api.runtimeMode() === "desktop" ? "Save a copy" : "Download"}</button><button class="danger-text" data-action="delete-file" data-name="${escape(dump.name)}" ${locked ? "disabled" : ""}>${locked ? "File in use" : "Delete dump"}</button></div></details></div></td></tr>`;
  }).join("")}</tbody></table></div><p class="table-count">${dumps.length} ${dumps.length === 1 ? "file" : "files"}${search ? ` matching "${escape(search)}"` : ""}</p>`;
}

export function dumpsView(state: Workspace, operations: Operations, search: string, sort: DumpSort, busy: Set<string>): string {
  return `<div class="library-page"><div class="page-intro"><span class="eyebrow">Dump library</span><h2>Ready for the next restore.</h2><p>${state.api.runtimeMode() === "desktop" ? "Dumps stored by this desktop app." : "Dumps stored on this server. Download a copy to keep it on your computer."}</p></div><div class="library-toolbar"><div class="search-field">${icon("search")}<label class="sr-only" for="dump-search">Search dumps</label><input type="search" id="dump-search" placeholder="Search by filename" value="${escape(search)}"/></div><label class="sort-field" for="dump-sort"><span>Sort</span><select id="dump-sort"><option value="newest" ${sort === "newest" ? "selected" : ""}>Newest modified</option><option value="oldest" ${sort === "oldest" ? "selected" : ""}>Oldest modified</option><option value="name" ${sort === "name" ? "selected" : ""}>Filename</option><option value="size" ${sort === "size" ? "selected" : ""}>Largest first</option></select></label></div>${state.dumps.error ? notice({ kind: "error", text: state.dumps.error }) : ""}<div id="dump-rows">${dumpRows(state, operations, search, sort, busy)}</div></div>`;
}
