import { dropExplanation, fileFormat, type Workspace } from "../app/state";
import type { Operations } from "../app/operations";
import { databasePicker } from "../components/database-picker";
import { bytes, engineName, escape, icon, notice } from "../components/html";
import { customSelect } from "../components/select";
import { operationResult } from "../components/shell";

export function restoreView(state: Workspace, operations: Operations): string {
  const result = operations.records.find(record => record.kind === "restore");
  const step = state.restoreStep;
  return `<ol class="restore-steps" aria-label="Restore steps">${["Source", "Target", "Review"].map((label, index) => `<li class="${step === index + 1 ? "current" : step > index + 1 ? "complete" : ""}" ${step === index + 1 ? 'aria-current="step"' : ""}><span>${step > index + 1 ? icon("check") : index + 1}</span>${label}</li>`).join("")}</ol>
    ${notice(state.restoreNotice)}${step === 1 ? sourceView(state) : step === 2 ? targetView(state) : reviewView(state, operations)}
    ${result ? `<div class="latest-result" aria-live="polite">${operationResult(result, state.api.runtimeMode() === "desktop")}</div>` : ""}`;
}

function sourceView(state: Workspace): string {
  const source = state.source;
  const library = state.sourceMode === "library";
  const desktop = state.api.runtimeMode() === "desktop";
  return `<div class="section-heading"><span class="section-icon">${icon("file")}</span><div><h2>Choose a source</h2><p>Select the file you want to restore.</p></div></div><div class="source-modes" role="group" aria-label="Dump source"><button id="source-file" class="${!library ? "selected" : ""}" aria-pressed="${!library}" data-action="source-mode" data-mode="file">${icon("file")} Choose file</button><button id="source-library" class="${library ? "selected" : ""}" aria-pressed="${library}" data-action="source-mode" data-mode="library">${icon("folder")} From dump library</button></div>
    ${library ? `<div class="field"><div class="field-heading"><label for="restore-library">Stored dump</label><button class="text-button" data-action="refresh-dumps" ${state.dumps.loading ? "disabled" : ""}>${icon("refresh")} Refresh</button></div>${customSelect({ id: "restore-library", label: "Stored dump", value: source?.library ? source.name : "", icon: "file", options: [{ value: "", label: state.dumps.loading ? "Loading dumps..." : "Choose a stored dump" }, ...state.dumps.data.map(dump => ({ value: dump.name, label: dump.name, description: bytes(dump.size) }))] })}${!state.dumps.data.length && !state.dumps.loading ? '<p class="field-help">No stored dumps. Choose a local file or export a database first.</p>' : ""}${state.dumps.error ? notice({ kind: "error", text: state.dumps.error }) : ""}</div>` : `<div class="file-dropzone" id="file-dropzone">${icon("restore")}<strong>${desktop ? "Choose a dump from your computer" : "Drop a dump file here"}</strong><span>${desktop ? "A native file picker will open." : "or browse your computer"}</span><button id="choose-source" data-action="choose-file">Choose file</button><input id="restore-file" class="sr-only" tabindex="-1" type="file" accept=".sql,.dump,.backup,.pgdump" aria-label="Source dump file"/><span class="field-help">.sql, .dump, .backup, .pgdump</span></div>`}
    ${source ? `<div class="selected-file">${icon("file")}<div><strong class="mono">${escape(source.name)}</strong><span>${source.size !== undefined ? `${bytes(source.size)} · ` : ""}${fileFormat(source.name) === "sql" ? "SQL file" : "Custom archive"} · inferred from extension</span></div><button class="icon-button" data-action="clear-source" aria-label="Remove selected source">${icon("close")}</button></div>` : ""}
    <p class="field-help">${!desktop && source && !source.library ? "The file will be uploaded for this restore after review. It will not be added to the dump library." : "Choose a dump created for the same engine as your target database."}</p><div class="operation-footer"><span></span><button class="primary" id="restore-next-source" data-action="restore-next" ${!source ? "disabled" : ""}>Choose target ${icon("chevron")}</button></div>`;
}

function targetView(state: Workspace): string {
  return `<div class="section-heading"><span class="section-icon">${icon("database")}</span><div><h2>Choose the target</h2><p>This is the database the restore will write to.</p></div></div><div class="field"><label for="restore-profile">Profile</label>${customSelect({ id: "restore-profile", label: "Profile", value: state.selectedName, icon: "database", options: [{ value: "", label: "Choose a profile" }, ...state.profiles.data.map(profile => ({ value: profile.name, label: profile.name, description: `${engineName(profile.engine)} · ${profile.host}` }))] })}${!state.profiles.data.length ? '<button class="text-button" data-action="new-profile">Add a profile</button>' : ""}</div>
    ${state.profileLoading ? '<p class="loading-line"><span class="spinner"></span> Loading profile...</p>' : ""}${state.profileError ? notice({ kind: "error", text: state.profileError }) : ""}${databasePicker(state)}
    ${state.profile ? `<div class="target-address">${icon("database")}<code>${escape(state.profile.connection.user)}@${escape(state.profile.connection.host)}:${state.profile.connection.port}</code><span>${escape(engineName(state.profile.engine))}</span></div><label class="check-field"><input id="drop-existing" type="checkbox" ${state.dropExisting ? "checked" : ""}/><span><strong>Drop existing objects before restore</strong><span>${escape(dropExplanation(state.profile.engine, fileFormat(state.source?.name || "")))}</span></span></label><p class="field-help">SQL files may contain destructive statements even when this option is off.</p>` : ""}
    <div class="operation-footer"><button data-action="restore-back">Back</button><button class="primary" id="restore-next-target" data-action="restore-next" ${!state.profile || !state.session?.database.trim() ? "disabled" : ""}>Review restore ${icon("chevron")}</button></div>`;
}

function reviewView(state: Workspace, operations: Operations): string {
  const review = state.review;
  if (!review) return "";
  return `<div class="section-heading"><span class="section-icon">${icon("restore")}</span><div><h2>Review restore</h2><p>Check the source and target before continuing.</p></div></div>
    <dl class="review-summary"><dt>Source file</dt><dd class="mono">${escape(review.source.name)}</dd><dt>Format</dt><dd>${review.format === "sql" ? "SQL" : "PostgreSQL custom"} <span class="muted">· inferred from extension</span></dd><dt>Target profile</dt><dd>${escape(review.profileName)}</dd><dt>Engine</dt><dd>${escape(engineName(review.engine))}</dd><dt>Host</dt><dd class="mono">${escape(review.connection.host)}:${review.connection.port}</dd><dt>User</dt><dd class="mono">${escape(review.connection.user)}</dd><dt>Database</dt><dd class="mono target-database">${escape(review.connection.database)}</dd><dt>Drop existing</dt><dd>${review.dropExisting ? "Enabled" : "Off"}</dd></dl>
    ${review.format === "sql" ? `<label class="check-field"><input type="checkbox" id="restore-ack" ${state.acknowledged ? "checked" : ""}/><span><strong>Source engine not verified</strong><span>I confirm this SQL dump was created for ${escape(engineName(review.engine))}.</span></span></label>` : ""}
    ${review.dropExisting ? `${notice({ kind: "warning", text: dropExplanation(review.engine, review.format) })}<div class="field"><label for="restore-confirm-name">Type <strong class="mono">${escape(review.connection.database)}</strong> to confirm</label><input id="restore-confirm-name" value="${escape(state.confirmation)}" autocomplete="off" spellcheck="false"/></div>` : '<p class="field-help">SQL statements in the dump can change or remove existing data.</p>'}
    <div class="restore-warning">${icon("alert")}<p>This operation writes to <strong>${escape(review.connection.database)}</strong> on <strong>${escape(review.connection.host)}:${review.connection.port}</strong>.</p></div><div class="operation-footer"><button data-action="restore-back">Back</button><button id="restore-submit" class="${review.dropExisting ? "danger" : "primary"}" data-action="restore" ${!state.canRestore() || operations.active ? "disabled" : ""}>${icon("restore")} Restore into ${escape(review.connection.database)}</button></div>${operations.active ? '<p class="field-help">An operation is already running. Follow it in Activity.</p>' : ""}`;
}
