import type { Workspace } from "../app/state";
import type { Theme } from "../app/theme";
import { escape, icon, notice } from "../components/html";

export function settingsView(state: Workspace, theme: Theme): string {
  const health = state.health.data;
  return `<div class="settings-page"><section class="settings-section"><div class="settings-heading"><span class="section-icon">${icon("settings")}</span><div><h2>Engine tools</h2><p>Executables used on ${state.api.runtimeMode() === "desktop" ? "this computer" : "the server hosting just-db"}.</p></div></div>${state.engines.error ? notice({ kind: "error", text: state.engines.error }) : ""}${state.engines.loading && !state.engines.data.length ? '<p class="loading-line"><span class="spinner"></span> Checking tools...</p>' : state.engines.data.map(engine => `<article class="engine-tools"><header><span class="engine-symbol ${engine.name === "mysql" ? "mysql" : ""}">${engine.name === "postgres" ? "PG" : "MY"}</span><h3>${escape(engine.displayName)}</h3><span class="status-badge ${engine.ready ? "success" : "warning"}">${icon(engine.ready ? "check" : "alert")}${engine.ready ? "Tools available" : "Tools missing"}</span></header><div class="tools-rows">${(["dump", "restore", "client"] as const).map(kind => { const tool = engine.tools[kind]; return `<div class="tool-row"><span class="tool-kind">${kind}</span><div><strong class="mono">${escape(tool.name)}</strong>${tool.found ? `<code>${escape(tool.path || tool.name)}</code><span class="field-help">${escape(tool.version || "Version unavailable")}</span>` : '<p class="danger-text">Not found on the app host</p>'}</div><span class="${tool.found ? "success-text" : "warning-text"}">${icon(tool.found ? "check" : "alert")}<span class="sr-only">${tool.found ? "Found" : "Missing"}</span></span></div>`; }).join("")}</div></article>`).join("")}<p class="field-help">Client tools must be compatible with your database server version. Tool availability does not test the database connection.</p></section>
    <section class="settings-section"><div class="settings-heading"><span class="section-icon">${icon("sun")}</span><div><h2>Appearance</h2><p>Choose how just-db looks on this device.</p></div></div><div class="theme-options" role="group" aria-label="Appearance">${(["system", "light", "dark"] as const).map(value => `<button data-action="theme" data-theme="${value}" class="theme-option ${theme === value ? "selected" : ""}" aria-pressed="${theme === value}"><span class="theme-preview ${value}"><i></i><b></b></span>${value[0].toUpperCase() + value.slice(1)}${theme === value ? icon("check") : ""}</button>`).join("")}</div></section>
    <section class="settings-section"><div class="settings-heading"><span class="section-icon">${icon("folder")}</span><div><h2>Storage & app</h2><p>${state.api.runtimeMode() === "desktop" ? "Files stored by this desktop app." : "Paths are on the server, not your computer."}</p></div></div>${state.health.error ? `${notice({ kind: "error", text: state.health.error })}<button data-action="refresh-health">Retry app information</button>` : ""}${state.defaultsError ? `${notice({ kind: "warning", text: state.defaultsError })}<button data-action="refresh-defaults">Retry defaults</button>` : ""}<dl class="storage-details"><dt>Version</dt><dd>${escape(health?.version || "Loading...")}</dd><dt>Runtime</dt><dd>${state.api.runtimeMode() === "desktop" ? "Desktop" : "Web"}</dd><dt>Data folder</dt><dd class="mono">${escape(health?.dataDir || state.defaults?.dataDir || "Unavailable")}</dd><dt>Dump folder</dt><dd class="mono">${escape(health?.backupsDir || state.defaults?.backupsDir || "Unavailable")}</dd></dl>${state.api.runtimeMode() === "desktop" ? `<button data-action="open-folder">${icon("folder")} Open dumps folder</button>` : ""}<p class="settings-about">just-db exports and restores PostgreSQL and MySQL / MariaDB databases. A dump restores to the same engine it came from.</p></section></div>`;
}
